[package]
name = "ReactTestingLibrary"
version = "12.2.3"
content_root = "src"
files = [
    "*",
    "!**/__tests__/**",
]
publish = true
authors = [
    "Ignacio Falk <flakolefluk@gmail.com>",
    "Allan Jeremy <dev@allanjeremy.com>",
]
[dependencies.DomTestingLibrary]
version = "^8.14.6"

[dependencies.JestGlobals]
version = "^3.0.0"

[dependencies.LuauPolyfill]
version = "^1"

[dependencies.Promise]
version = "^3.3.0"

[dependencies.React]
version = "^17.0.1-rc.16"

[dependencies.ReactRoblox]
version = "^17.0.1-rc.16"

[dependencies.Scheduler]
version = "^17.0.1-rc.16"

[dependencies.Shared]
version = "^17.0.1-rc.16"
